### ISSUE TITLE
fix(boot): break cover_letter ↔ scoring.llm import cycle that blocks uvicorn --factory

### ISSUE THREAD

**Issue by q-user** [q-user/apply-pilot#225]
## Context

`docker compose up apply-pilot-api` fails on `main` (`2db873f`) with
`ImportError: cannot import name 'LLMClient' from partially initialized
module 'apply_pilot.features.scoring.llm' (most likely due to a circular
import)`. The container exited with code 1 on the first boot after M10
(#217/#220). `docker run apply-pilot:local python -c "from
apply_pilot.app import create_app"` succeeds, but `uvicorn
apply_pilot.app:create_app --factory` (and any `create_app()` call)
fails.

This means the api container has been silently broken since #220 (and
possibly earlier — repro is identical on `2db873f` with no uncommitted
changes). CI does not catch it because `pytest` boots the app via
`TestClient`, which exercises a different import path.

## Repro

```
docker compose up -d apply-pilot-api
docker logs --tail 30 apply-pilot-api
# → ImportError, container Exited (1)
```

A pure-Python repro (no compose env needed):

```
docker run --rm apply-pilot:local   python -c "import apply_pilot.app; apply_pilot.app.create_app()"
# → ImportError
```

## Root cause

`src/apply_pilot/app.py:236` does an eager
`from apply_pilot.features.admin import admin_web_router`, which loads
`admin.integrations`. The latter has a top-level
`from apply_pilot.features.scoring.llm import HttpLLMClient`
(`admin/integrations.py:37`). Loading `scoring.llm` triggers:

```
scoring.llm
  → scoring.prompts
    → sources.models
      → apply_worker.runtime
        → apply_worker.service
          → apply_worker.notifications
            → telegram.repository
              → telegram.bot
                → messaging.actions.accept
                  → messaging.actions.regenerate
                    → cover_letter.service  (top: from scoring.llm import LLMClient)
                      💥 LLMClient not yet bound on partially-initialised scoring.llm
```

The cycle `cover_letter ↔ scoring.llm` has always existed; it is masked
on `main` only when `matches.service` is loaded first (via
`apply_worker.runtime`), which warms the cover-letter import graph
before `admin.integrations` is reached. Touching any top-level import
in the chain (e.g. moving `MatchService` to lazy, as PR #220's
follow-up planned) unmasks it.

## Fix (proposed)

Make `HttpLLMClient` import in `admin/integrations.py` lazy:

```
# from apply_pilot.features.scoring.llm import HttpLLMClient
...
def _build_llm_checker() -> LlmChecker:
    from apply_pilot.features.scoring.llm import HttpLLMClient
    ...
```

This is the smallest, most local change. `HttpLLMClient` is only used
inside `LlmChecker` construction and is not part of the module's
public surface (not in `__all__`). `TYPE_CHECKING` would also work
if the type is only used in annotations; current usage in
`integrations.py` is a runtime constructor call, so a lazy
factory/function is the safer path.

Alternatives considered (more invasive, defer to M11):
- break the `apply_worker → cover_letter` leg by lazy-loading
  `TelegramAccountRepository` in `apply_worker/notifications.py`.
  Bigger blast radius.
- introduce a `scoring.llm` `__getattr__` proxy. New pattern, more
  review.

## Scope

- `src/apply_pilot/features/admin/integrations.py`: move
  `HttpLLMClient` import under lazy.
- New test `tests/features/admin/test_imports.py` (or extend an
  existing one) that imports `apply_pilot.app` and calls
  `create_app()` in-process to lock the boot path.
- Out of scope: M11 (`#206`) refactor of the apply-worker runtime;
  that work will likely re-touch the same import chain and should
  build on a clean boot.

## Acceptance

- `docker compose up -d apply-pilot-api` brings the container up
  healthy (no `Exited (1)`).
- `uvicorn apply_pilot.app:create_app --factory` reaches the
  "Uvicorn running on…" log line.
- `uv run pytest tests/` stays green.
- `uv run ruff check .`, `uv run ruff format --check .`, `uv run ty
  check src/` stay green (no new diagnostics).

## Out of scope / non-goals

- Decoupling `cover_letter` from `scoring.llm` (the deeper design
  fix). This issue just unblocks the boot path.
- M11 hh_apply adapter work (tracked in #206).

## Related

- #221 — import-graph test guard (different cycle: apply_worker ↔
  matches).
- #222 — MAX bot smoke boot (different process; the same defensive
  test pattern is useful but applies to a different entry point).
- #165 — earlier "Dockerfile CMD referenced non-existent
  apply_pilot.app:app" — also a boot-time regression; this issue is
  the next instance of the same class.
